global using Flurl;
global using Flurl.Http;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using KanonBot;
global using static KanonBot.Utils;
global using LanguageExt;
global using static LanguageExt.Prelude;
global using Serilog;
// global using global::System.IO;
// global using global::System.Net.Http;
